<a href="https://colab.research.google.com/github/b19szn/Data-Structures/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Array Iteration using regular for loop and using range for loop

In [2]:
#using regular for loop
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
for i in arr1:
  print(i)

#Using range for loop

arr1 = np.array([1,2,3,4,5,6])
for i in range(0,len(arr1),1):
  print(arr1[i])

1
2
3
4
5
6
1
2
3
4
5
6


Array Resize

In [6]:
import numpy as np

def resizeArray(arr,new_size):
  arr2 = np.array([0]*new_size)
  for i in range(len(arr)):
    arr2[i] = arr[i]
  return arr2

arr1 = np.array([1,2,3,4,5,6])
print(resizeArray(arr1,8))


[1 2 3 4 5 6 0 0]


Copy Array

In [8]:
def copyArray(arr):
  newArray = [None]*len(arr)
  for i in range(len(arr)):
    newArray[i] = arr[i]
  return newArray

Array Shifting Left And Right

In [3]:
#[5,3,9, 13 , 2]
#After Left Shift
#[3 , 9 , 13 ,2 , 0(None)]

import numpy as np
def LeftShift(arr):
  for i in range(1,len(arr)):
    arr[i-1] = arr[i]
  arr[len(arr)-1] = 0 #None
  return arr

arr = np.array([5 , 3 , 9 , 13 , 2])
print(LeftShift(arr))


[ 3  9 13  2  0]


In [6]:
#[5,3,9, 13 , 2]
#After Right Shift
#[0(None), 5 , 3 , 9 , 13]

import numpy as np
def RightShift(arr):
  for i in range(len(arr)-1,0,-1):
    arr[i] = arr[i-1]
  arr[0] = 0
  return arr

arr = np.array([5,3,9,13,2])
print(RightShift(arr))

[ 0  5  3  9 13]


Array Rotate Left and Right



In [7]:
#Array [ 5 3 9 13 2]
#After Left Rotate
#Array [3 9 13 2 5]

import numpy as np

def RotateLeft(arr):
  temp = arr[0]
  for i in range(1,len(arr)):
    arr[i-1] = arr[i]
  arr[len(arr)-1] = temp
  return arr

arr = np.array([5 , 3 , 9 , 13 , 2])
print(RotateLeft(arr))


[ 3  9 13  2  5]


In [12]:
#Array [5 3 9 13 2]
#After Right Rotate
#Array [2 5 3 9 13]

import numpy as np

def RotateRight(arr):
  temp = arr[len(arr)-1]
  for i in range(len(arr)-1,0,-1):
    arr[i] = arr[i-1]
  arr[0] = temp
  return arr

arr =np.array([5 , 3 , 9 , 13 , 2])
print(RotateRight(arr))


[ 2  5  3  9 13]


Array Reverse : Out OF Place and In-Place

In [15]:
#Reverse Out Of Place
#Arr = [10 20 30 40 50]
#After Reverse
#RevArr = [50 40 30 20 10]

def reversearrayoutofplace(arr):
  revArr = [None]*len(arr)
  i = 0
  j = len(arr) - 1
  while i<len(arr):
    revArr[i] = arr[j]
    i += 1
    j -= 1
  return revArr



arr = np.array([10 ,20 , 30 , 40 , 50])
print(reversearrayoutofplace(arr))



[50, 40, 30, 20, 10]


In [17]:
#Reverse In Place
#Arr = [10 20 30 40 50]
#After Reverse
#RevArr = [50 40 30 20 10]
import numpy as np

def reversearrayinplace(arr):
  i = 0
  j = len(arr)-1
  while i<j:
    temp = arr[i]
    arr[i] = arr[j]
    arr[j] = temp
    i+=1
    j-=1
  return arr



arr = np.array([10 , 20 , 30 , 40, 50])
print(reversearrayinplace(arr))





[50 40 30 20 10]
