<a href="https://colab.research.google.com/github/b19szn/Data-Structures/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Array Iteration using regular for loop and using range for loop

In [ ]:
#using regular for loop
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
for i in arr1:
  print(i)

#Using range for loop

arr1 = np.array([1,2,3,4,5,6])
for i in range(0,len(arr1),1):
  print(arr1[i])

1
2
3
4
5
6
1
2
3
4
5
6


Array Resize

In [ ]:
import numpy as np

def resizeArray(arr,new_size):
  arr2 = np.array([0]*new_size)
  for i in range(len(arr)):
    arr2[i] = arr[i]
  return arr2

arr1 = np.array([1,2,3,4,5,6])
print(resizeArray(arr1,8))


[1 2 3 4 5 6 0 0]


Copy Array

In [ ]:
def copyArray(arr):
  newArray = [None]*len(arr)
  for i in range(len(arr)):
    newArray[i] = arr[i]
  return newArray

Array Shifting Left And Right

In [ ]:
#[5,3,9, 13 , 2]
#After Left Shift
#[3 , 9 , 13 ,2 , 0(None)]

import numpy as np
def LeftShift(arr):
  for i in range(1,len(arr)):
    arr[i-1] = arr[i]
  arr[len(arr)-1] = 0 #None
  return arr

arr = np.array([5 , 3 , 9 , 13 , 2])
print(LeftShift(arr))


[ 3  9 13  2  0]


In [ ]:
#[5,3,9, 13 , 2]
#After Right Shift
#[0(None), 5 , 3 , 9 , 13]

import numpy as np
def RightShift(arr):
  for i in range(len(arr)-1,0,-1):
    arr[i] = arr[i-1]
  arr[0] = 0
  return arr

arr = np.array([5,3,9,13,2])
print(RightShift(arr))

[ 0  5  3  9 13]


Array Rotate Left and Right



In [ ]:
#Array [ 5 3 9 13 2]
#After Left Rotate
#Array [3 9 13 2 5]

import numpy as np

def RotateLeft(arr):
  temp = arr[0]
  for i in range(1,len(arr)):
    arr[i-1] = arr[i]
  arr[len(arr)-1] = temp
  return arr

arr = np.array([5 , 3 , 9 , 13 , 2])
print(RotateLeft(arr))


[ 3  9 13  2  5]


In [ ]:
#Array [5 3 9 13 2]
#After Right Rotate
#Array [2 5 3 9 13]

import numpy as np

def RotateRight(arr):
  temp = arr[len(arr)-1]
  for i in range(len(arr)-1,0,-1):
    arr[i] = arr[i-1]
  arr[0] = temp
  return arr

arr =np.array([5 , 3 , 9 , 13 , 2])
print(RotateRight(arr))


[ 2  5  3  9 13]


Array Reverse : Out OF Place and In-Place

In [ ]:
#Reverse Out Of Place
#Arr = [10 20 30 40 50]
#After Reverse
#RevArr = [50 40 30 20 10]

def reversearrayoutofplace(arr):
  revArr = [None]*len(arr)
  i = 0
  j = len(arr) - 1
  while i<len(arr):
    revArr[i] = arr[j]
    i += 1
    j -= 1
  return revArr



arr = np.array([10 ,20 , 30 , 40 , 50])
print(reversearrayoutofplace(arr))



[50, 40, 30, 20, 10]


In [ ]:
#Reverse In Place
#Arr = [10 20 30 40 50]
#After Reverse
#RevArr = [50 40 30 20 10]
import numpy as np

def reversearrayinplace(arr):
  i = 0
  j = len(arr)-1
  while i<j:
    temp = arr[i]
    arr[i] = arr[j]
    arr[j] = temp
    i+=1
    j-=1
  return arr



arr = np.array([10 , 20 , 30 , 40, 50])
print(reversearrayinplace(arr))





[50 40 30 20 10]


#if size == len(arr):
#rint("No Space Left. Insertion Failed")
#return **arr**



In [55]:
#Main Task is Basically arr[size] = elem
import numpy as np
def insert_at_the_end(arr, size, elem):
    if size >= len(arr):
        new_arr = np.zeros(size + 1, dtype=int)
        for i in range(len(arr)):
            new_arr[i] = arr[i]
        arr = new_arr
    arr[size] = elem
    return arr

arr= np.zeros(4, dtype=int)
arr[0], arr[1], arr[2] = 4, 6, 5
print(arr)
print(insert_at_the_end(arr, 3, 15)) #array, size, elem
print(insert_at_the_end(arr, 4, 25)) #array, size, elem

[4 6 5 0]
[ 4  6  5 15]
[ 4  6  5 15 25]


In [59]:
#Insert elemrnt in any Any Particular Index
import numpy as np

def insert_at_the_end(arr, size, elem, index):
    if size >= len(arr):
        new_arr = np.zeros(size + 1, dtype=int)
        for i in range(len(arr)):
            new_arr[i] = arr[i]
        arr = new_arr
    for i in range(size, index, -1): #must should be rightshift
        arr[i] = arr[i-1]
    arr[index] = elem
    return arr

arr = np.zeros(4, dtype=int)
arr[0], arr[1], arr[2] = 4, 6, 5
print(arr)
print(insert_at_the_end(arr, 3, 15, 0))
print(insert_at_the_end(arr, 4, 25, 2))

[4 6 5 0]
[15  4  6  5]
[15  4 25  6  5]


In [60]:
#Deleting last element
def delete_last_element (arr, size):
   if size == 0:
      return "Deletion Not Possible"
   arr[size-1]= 0
   return arr
arr= np.zeros(4, dtype=int)
arr[0], arr[1], arr[2] = 4, 6, 5
print(arr)
print(delete_last_element(arr, 3)) #array, size
print(delete_last_element(arr, 2)) #array, size

[4 6 5 0]
[4 6 0 0]
[4 0 0 0]


In [65]:
#deleting any element

def delete_any_element(arr,size,index):
  if size == 0:
    return "Deletion not possible"

  for i in range(index,size,1): #Must Be Left Shifted
     arr[i] = arr[i+1]
  arr[size-1] = 0
  return arr

arr= np.zeros(5, dtype=int)
arr[0], arr[1], arr[2], arr[3] = 4, 6, 5, 2
print(arr)
print(delete_any_element(arr, 4, 0)) #array, size, index
print(delete_any_element(arr, 3, 2)) #array, size, index

[4 6 5 2 0]
[6 5 2 0 0]
[6 5 0 0 0]
